### ISSUE TITLE
requireUserVerification is called twice

### ISSUE THREAD

**Issue by nielsvanrijn** [lyokato/WebAuthnKit#16]
The `create()` and `get()` require UserVerification to be called twice. 
So A passcode or FaceID is prompted twice.
if it only prompts once `askUserToCreateNewCredential` stops at with error `unknown`

It seems that it has something to do with permissions. I think one UserVerification is to allow the use of FaceID(for example) and the next is is the "real" UserVerificaton.

Here is a video of what I mean. It doen't show errors but when I tap register a second time I only get prompted once for UserVerification and `askUserToCreateNewCredential` stops at with error `unknown`.
https://streamable.com/wtg28y

**Comment by JaapWijnen** [comment]
Should be fixed by #17
